# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'Ps-ae-dev-test-SC'
    appType: 'functionAppLinux'
    appName: 'uyrtdfliopymlh'
    package: '$(System.DefaultWorkingDirectory)'

# - task: DotNetCoreCLI@2
#   inputs:
#     command: 'publish'
#     projects: '*.csproj'
#     arguments: '--configuration Release --output publish_output'




- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: "$(System.DefaultWorkingDirectory)"
    includeRootFolder: false
    archiveFile: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"



- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip'




